- tutorials/README.md
> Add README file to tutorial dir

- tutorials/generative/3d_ldm/3d_ldm_tutorial.ipynb
- tutorials/generative/3d_ldm/3d_ldm_tutorial.py
> Add more content to tutorial

- generative/networks/blocks/selfattention.py
- generative/networks/blocks/transformerblock.py
- generative/networks/nets/transformer.py
- requirements-dev.txt
> Add flash attention to Transformers

- generative/metrics/fid.py
- tests/test_compute_fid_metric.py
> Adopt exact computation of FID

- generative/losses/adversarial_loss.py
When using GPU devices other than "cuda" or "cuda:0", calling the loss will raise a device mismatch error. The change makes the devices for zero or target tensors consistent with inputs.
> Fix CUDA device mismatch

- generative/networks/nets/diffusion_model_unet.py
Fixes #351. Also adds a check that xformers is installed if `use_flash_attention=True`; previously this check was not done and it errored out if xformers was not installed.
> Fix grad strides warning when using ddp

- generative/networks/nets/__init__.py
- generative/networks/nets/controlnet.py
- generative/networks/nets/diffusion_model_unet.py
- tests/test_controlnet.py
> Add ControlNet

- generative/losses/perceptual.py
- tests/test_perceptual_loss.py
Fixes #389 
This PR is used to enable torchvision's version of resnet50 on `PerceptualLoss`.
Users can also determine which pretrained weights is used.
> 389 add torchvision resnet50 support

- requirements.txt
- setup.py
> Use monai instead of monai-weekly in the requirements

- generative/inferers/inferer.py
- tests/test_diffusion_inferer.py
- tests/test_latent_diffusion_inferer.py
https://github.com/Project-MONAI/GenerativeModels/issues/410 add different conditioning modes (e.g., "concat") in `DiffusionInferer` and `LatentDiffusionInferer`.
> support diff cond type in infererer

- generative/networks/nets/autoencoderkl.py
- generative/networks/nets/vqvae.py
- tests/test_autoencoderkl.py
- tests/test_vqvae.py
https://github.com/Project-MONAI/GenerativeModels/issues/410 support ConvTranspose to avoid F.interpolate limitation and activation checkpointing to save memeory.
> support convtranspose and activation checkpointing

- generative/networks/blocks/__init__.py
- generative/networks/blocks/encoder_modules.py
- tests/test_encoder_modules.py
Follow the discussion at https://github.com/Project-MONAI/GenerativeModels/issues/410 and add the spatial rescaler implementation.
> add spatial rescaler

- generative/inferers/inferer.py
- tests/test_latent_diffusion_inferer.py
Add padding and cropping options to the Latent Diffusion Inferer. Includes:
- Modification of the init, call and sample methods, allowing to pad and then crop the LDM latent space
- If these shape parameters aren't specified, this works as usual (they are defaulted to None).
- Added a test on the test_latent_diffusion_inferer trying this new scenario both with VAE+DM and VQVAE+DM.
> Add pad and cropping options to the Latent Diffusion Inferer (+ test).

- generative/networks/blocks/encoder_modules.py
- generative/networks/blocks/spade_norm.py
- generative/networks/nets/spade_network.py
- tests/test_spade_vaegan.py
> Fixes SPADE flake8

- generative/inferers/inferer.py
Added partial to SPADE autoencoder in the sample methods.
> Added SPADE functionality on the decode call for the sample methods.

- setup.cfg
- setup.py
> Update setuppy and pyprojecttoml

- generative/networks/schedulers/ddim.py
In `reversed_step,` when traversing the timesteps all the way to the last, an exception is raised by exceeding the boundaries of the `alphas_cumprod`. This is now fixed by setting the first value of the `alphas_cumprod` to either zero or to the second-to-last element. The behavior is set by the init argument `set_alpha_to_one` which control the behavior regarding the first element in the array. 
Also, names of local variables in the function are fixed.
Linked to: [issue 446](https://github.com/Project-MONAI/GenerativeModels/issues/446)
> 446 Fix the way reversed_step in DDIM treats the first alpha in alphas_cumprod

- generative/networks/nets/patchgan_discriminator.py
Fixes #451 
Also keeping track of in this [MONAI issue](https://github.com/Project-MONAI/MONAI/issues/7336)
> Add warning when initialising the patchgan discriminator with batchnorm in a distributed environment

- generative/networks/nets/patchgan_discriminator.py
- tests/test_patch_gan.py
- tutorials/generative/2d_spade_gan/2d_spade_vae.py
Added features according to issue #475 leaving the default behaviour the same. According to my testing it should be as fast as the previous implementation.
Additionally, I fixed the 2D_spade_VAE.py tutorial, as it didn't work on my Windows laptop.
> 475 add different downsampling methods to patch gan discriminator

- generative/networks/nets/patchgan_discriminator.py
- generative/networks/nets/vqvae.py
- generative/networks/schedulers/ddim.py
- generative/networks/schedulers/ddpm.py
In response to discussion #492  and issue #494:
- modification of DDPM and DDIM. We added arguments clip_sample_min and clip_sample_max, so that the user can choose to clip, but specify by which values (originally, it was done with -1 and 1, but this has proven ineffective with certain image ranges and with latent models).
- VQ-VAE was missing an import 
- Patch-GAN and VQVAE have been reformatted after running autofix.
> Allowing sample clipping values besides clip_sample True/False 
